Repository xTaromarux/Maszyna-W-Remake, pull requests merged in 2025-05, with the labels that each got.

#7 Refactor MainComponent: Modular Sub-components, Unified Signal Handling & SCSS Modularization
  src/components/BusSignal.vue
  src/components/CalcSection.vue
  src/components/CounterComponent.vue
  src/components/Main.vue
  src/components/MemorySection.vue
  src/components/RegisterComponent.vue
  src/components/RegisterISection.vue
  src/components/SignalButton.vue
  src/components/XRegisterSection.vue
  src/components/YRegisterSection.vue
  src/styles/components/_aiChat.scss
  src/styles/components/_bus.scss
  src/styles/components/_calc.scss
  src/styles/components/_console.scss
  src/styles/components/_counter.scss
  src/styles/components/_inputs.scss
  src/styles/components/_memory.scss
  src/styles/components/_settings.scss
  src/styles/components/_signals.scss
  src/styles/components/_ui.scss
  src/styles/components/arrows.scss
  src/styles/main.scss
  src/utils/data/commands.js
Labels: refactoring

#8 refactor(TopBar): moved toolbar template to UI folder, Refs #3
  src/components/AiChat.vue
  src/components/Console.vue
  src/components/Main.vue
  src/components/UI/TopBar.vue
Labels: DRAFT

#34 9 refactorapp finalize refactoring of the entire application
  src/components/ExecutionControls.vue
  src/components/Main.vue
  src/components/ProgramEditor.vue
  src/components/Settings.vue
  src/styles/components/_inputs.scss
Labels: refactoring, backstage
